version: '3' 
services: 
  zookeeper: 
    image: jplock/zookeeper
    ports: 
        - "2181:2182" 
  
  kafka: 
    image: wurstmeister/kafka:2.12-2.1.1 
    depends_on: 
        - "zookeeper" 
    restart: on-failure
    ports: 
        - "9092:9092"
    environment: 
        KAFKA_BROKER_ID: 1
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,EXTERNAL_CONNECTION://${IP_ADDR}:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL_CONNECTION:PLAINTEXT
        KAFKA_LISTENERS: PLAINTEXT://kafka:19092,EXTERNAL_CONNECTION://:9092
        KAFKA_CREATE_TOPICS: "ndwspeed:1:1,ndwflow:1:1,metrics:1:1,output:1:1,aggregation-data-topic:1:1,speed-through-topic:1:1,flow-through-topic:1:1" 
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
    volumes: 
        - /var/run/docker.sock:/var/run/docker.sock

  
  jobmanager:
    image: flink:1.11.3-scala_2.11
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        metrics.latency.granularity: single 
        jobmanager.rpc.address: jobmanager 
    volumes:
      - data:/mnt/data

  
  
  taskmanager:
    image: flink:1.11.3-scala_2.11
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - |
        FLINK_PROPERTIES=
        metrics.latency.granularity: single 
        jobmanager.rpc.address: jobmanager 
    volumes:
      - data:/mnt/data

  
volumes:
  # This volume will show with 'docker volume ls' as 'docker_data'
  data:
