version: '2' 
services:
  
  
  zookeeper: 
    image: jplock/zookeeper
    ports: 
      - "2181:2181"
  
  
  
  kafka: 
    image: wurstmeister/kafka:2.12-2.1.1
    depends_on: 
      - zookeeper 
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "ndwspeed:1:1,ndwflow:1:1,metrics:1:1,aggregation-data-topic:1:1,speed-through-topic:1:1,flow-through-topic:1:1" 
      KAFKA_ADVERTISED_HOST_NAME: localhost #192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

